# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190320_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=posts.models.Post.get_inf_time, null=True),
        ),
    ]
